######################################################################
# Automatically generated by qmake (3.0) ??? ??? 4 23:12:05 2016
######################################################################

TEMPLATE = app
TARGET = hadamard_tbb
INCLUDEPATH += .
QT += opengl

# Input
HEADERS += hadamard.h pic.h widget.h
SOURCES += hadamard.cpp main.cpp pic.cpp widget.cpp
