######################################################################
# Automatically generated by qmake (3.0) ??? ??? 5 19:50:07 2016
######################################################################

TEMPLATE = app
TARGET = hadamard_tbb
INCLUDEPATH += .
QT += opengl

# Input
HEADERS += hadamard.h pic.h widget.h
SOURCES += main.cpp pic.cpp widget.cpp
